# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joints controllers, each joint with individual command
base_position_controller:
  type: position_controllers/JointPositionController
  joint: base
  pid: {p: 50, i: 0, d: 20}  #d: 10

shoulder_position_controller:
  type: position_controllers/JointPositionController
  joint: shoulder
  pid: {p: 1000, i: 0, d: 100}   # d_ 100 i: 0 p: 1000

elbow_position_controller:
  type: position_controllers/JointPositionController
  joint: elbow
  pid: {p: 1000, i: 1, d: 50} # p:500 #p: 30

pitch_position_controller:
  type: position_controllers/JointPositionController
  joint: pitch
  pid: {p: 100, i: 0, d: 10}

roll_position_controller:
  type: position_controllers/JointPositionController
  joint: roll
  pid: {p: 50, i: 1, d: 10}


# Joint trajectory controller, all joints controller
trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base
    - shoulder
    - elbow
    - pitch
    - roll
