# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  base:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  elbow:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  gripper_finger_left_joint:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  gripper_finger_right_joint:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  pitch:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  roll:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5
  shoulder:
    has_velocity_limits: true
    max_velocity: 0.37
    has_acceleration_limits: true
    max_acceleration: 1.5