controller_list:
  - name: /scorbot/trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base
      - shoulder
      - elbow
      - pitch
      - roll