joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joints controllers, each joint with individual command
base_controller:
  type: position_controllers/JointPositionController
  joint: base
  encoder_ticks_per_revolution: 46080
  current_limit: 2.5

shoulder_controller:
  type: position_controllers/JointPositionController
  joint: shoulder
  encoder_ticks_per_revolution: 46080
  current_limit: 2.5

elbow_controller:
  type: position_controllers/JointPositionController
  joint: elbow
  encoder_ticks_per_revolution: 46080
  current_limit: 2.5

pitch_controller:
  type: position_controllers/JointPositionController
  joint: pitch
  encoder_ticks_per_revolution: 19200
  current_limit: 1.875

roll_controller:
  type: position_controllers/JointPositionController
  joint: roll
  encoder_ticks_per_revolution: 9600
  current_limit: 1.0

# Joint trajectory controller, all joints controller
trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base
    - shoulder
    - elbow
    - pitch
    - roll

gripper_controller:
  type: effort_controllers/JointEffortController
  joint: gripper_finger_right_joint

scorbot_control_hw:
  loop_frequency: 1000
  cycle_time_error_threshold: 0.002
  ethercat_iface: eth0

